name: Setup Node and PNPM
description: Setup Node.js and PNPM with caching

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "22"
  pnpm-version:
    description: PNPM version
    required: false
    default: "9"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
